    default: &default
      adapter: postgresql
      encoding: unicode
      host: portfolio.crtlvydt6zsr.ap-northeast-1.rds.amazonaws.com
      username: root  
      password: Shota033           
      pool: 5

    development:
      <<: *default
      database: porfolio_development

    test:
      <<: *default
      database: portfolio_test

    production:
      <<: *default
      database: portfolio
