default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: app_user_role
  password: aaaa
  pool: 5

development:
  <<: *default
  database: myapp_development


test:
  <<: *default
  database: myapp_test
